version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew build
      - printf '{"ImageURI":"image_URI"}' > imageDetail.json
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - imageDetail.json
    - build/libs/arduino-maker-bff-1.0.0.jar