# Use root/example as user/password credentials
version: '3.1'

networks:
  mongodb_network:
    driver: bridge
    ipam:
      driver: bridge
      config:
        - subnet: 10.10.10.0/24

services:

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    networks:
      - mongodb_network
    ports:
      - 27017:27017
    volumes:
      - /home/analucia/docker/volumes/mongodb/database:/data/db
    environment:
      MONGO_INITDB_DATABASE: "dev"
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "arduino_maker_bff"

  mongodb-express:
    image: mongo-express
    container_name: mongodb-express
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
      - 8081:8081
    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
#      ME_CONFIG_MONGODB_ADMINPASSWORD: "arduino_maker_bff"
#      ME_CONFIG_MONGODB_URL: "mongodb://admin:arduino_maker_bff@dev:27017"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "arduino_maker_bff"
      ME_CONFIG_BASICAUTH_USERNAME: "admin"
      ME_CONFIG_BASICAUTH_PASSWORD: "arduino_maker_bff"